In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [1]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
    to print the data types of both the variables.

In [ ]:
list_ variable will have the data type list, 
while the array_list variable will have the data type numpy.ndarray indicating a NumPy array.

In [7]:
type(list_)

list

In [9]:
type(array_list)

numpy.ndarray

In [ ]:
-----------------------------------------------------------------------------------------------------------------------------

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [10]:
print("Data type of element of list_ :  ")
for i in list_:
    print(type(i))
    
print("Data type of element of array_list : ")
for i in array_list :
    print(type(i))

Data type of element of list_ :  
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of element of array_list : 
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
-----------------------------------------------------------------------------------------------------------------------------

In [ ]:
Q3. Considering the following changes in the variable, array_list:
    array_list = np.array(object = list_, dtype = int)
    
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
type(array_list)

numpy.ndarray

In [13]:
print("Data type of element of array_list : ")
for i in array_list :
    print(type(i))

Data type of element of array_list : 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list after
applying the dtype=int parameter in the NumPy array creation.

In [ ]:
-----------------------------------------------------------------------------------------------------------------------------

In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [15]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

In [ ]:
-----------------------------------------------------------------------------------------------------------------------------

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
    [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
-----------------------------------------------------------------------------------------------------------------------------

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
    [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])